

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import java.util.ArrayList;
import java.util.Scanner;
import java.sql.*;
import java.util.Random;
/**
 *
 * @author aleda
 */
public class NewJFrame extends javax.swing.JFrame {
    public String nm;
    public Connection conn;
    public User us;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        this.conn = null;
        this.nm = new Scanner(System.in).nextLine();
        System.out.println(this.nm);
        Statement stmt = null;
        ResultSet rs = null;
        initComponents();
        try{

        this.conn = DriverManager.getConnection(
        "jdbc:mysql://localhost/vaseis_dedomenwn_sept","root","Den8aKsexasw");
      }catch(SQLException ex){}


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(54, 54, 54)
                .addComponent(jButton2)
                .addGap(57, 57, 57)
                .addComponent(jButton3)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

      try {
      Statement stmt = conn.createStatement();
      //pairnw etairia
      ResultSet rs = stmt.executeQuery("select t1.employeeUsername,t2.password,t2.name,t2.surname,t2.email ,t1.* from (select * from employee as emp where employeeUsername LIKE \'%"
                                       +this.nm.toString()+"%\') as t1 INNER JOIN (select us.email,us.username,us.name ,us.surname,us.password from user as us) as t2"
                                       +" ON t1.employeeUsername LIKE t2.username");
      rs = stmt.getResultSet();

      //pairnw metadata
      ResultSetMetaData metadata = rs.getMetaData();
      int numberOfColumns = metadata.getColumnCount();
      ArrayList<String>inf = new ArrayList<String>();
      rs.next();

      for (int i = 1; i <= numberOfColumns; i++)
        {
          if(rs.getObject(i)==null){
              inf.add("0");
          }else{
            inf.add(rs.getObject(i).toString());
          }
        }
       Employee emp = new Employee(inf.get(1),inf.get(2),inf.get(3),inf.get(4),inf.get(5), Integer.parseInt(inf.get(11)),inf.get(7),inf.get(8)
                                  ,inf.get(9),inf.get(10),inf.get(12));
       emp.get_my_info(conn);
       JOptionPane.showMessageDialog(null, "Welcome " + "!", "Successful Login", JOptionPane.PLAIN_MESSAGE);
      }
      catch ( SQLException ex ) {
        // handle any errors
        System.out.println("SQLException: " + ex.getMessage());
        System.out.println("SQLState: " + ex.getSQLState());
        System.out.println("VendorError: " + ex.getErrorCode());
      }


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration
}
